# Stage 1: Base image with essential tools for backend
FROM ubuntu:22.04 AS base

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    MUSCLE_VERSION=3.8.1551 \
    LINEARDESIGN_REPO=https://github.com/LinearDesignSoftware/LinearDesign.git

# Install general dependencies for backend
RUN apt-get update && \
    apt-get install -y \
    locales \
    openjdk-21-jdk \
    curl \
    wget \
    build-essential \
    python2 \
    python3.11 \
    python3-pip \
    git && \
    apt-get clean
    
# Set locale to Korean
RUN locale-gen ko_KR.UTF-8 && \
    update-locale LANG=ko_KR.UTF-8 LANGUAGE=ko_KR:ko LC_ALL=ko_KR.UTF-8

# # Set environment variables for locale
ENV LANG=ko_KR.UTF-8 \
    LANGUAGE=ko_KR:ko \
    LC_ALL=ko_KR.UTF-8

# Install Python packages for bioinformatics (if needed by the backend)
RUN pip3 install biopython==1.83 requests==2.32.3

# Install MUSCLE tool
RUN mkdir /muscle && cd /muscle && \
    wget https://www.drive5.com/muscle/muscle_src_${MUSCLE_VERSION}.tar.gz && \
    tar -xvzf muscle_src_${MUSCLE_VERSION}.tar.gz && \
    make && \
    cp muscle /usr/local/bin/ && \
    cd .. && rm -rf /muscle

# Install LinearDesign for bioinformatics analysis
RUN git clone ${LINEARDESIGN_REPO} /LinearDesign && \
    cd /LinearDesign && \
    make && \
    cd ..

# Stage 2: Build the backend (Spring Boot)
FROM base AS backend

# Set the working directory to the backend folder
WORKDIR /VirusDecode/backend

# Copy the backend files from the host machine
COPY . /VirusDecode/backend

# Grant executable permissions for Gradle wrapper
RUN chmod +x ./gradlew

# Build the Spring Boot application
RUN ./gradlew assemble

# Final image for deployment
FROM base AS deploy

# Set the working directory for the final image
WORKDIR /app/backend

# Copy the jar file from the builder stage
COPY --from=backend /VirusDecode/backend/build/libs/virusdecode.jar /app/backend/virusdecode.jar
COPY --from=backend /VirusDecode/backend/virusdecode.py /app/backend/virusdecode.py

# Expose the backend port
EXPOSE 8080

# Set the entry point for the backend application
CMD ["java", "-jar", "/app/backend/virusdecode.jar"]